### ISSUE TITLE
error: 'BUFFER_LENGTH' was not declared in this scope

### ISSUE THREAD

**Issue by Krister-Johansson** [Seeed-Studio/Seeed_ICM20600_AK09918#3]
I get` error: 'BUFFER_LENGTH' was not declared in this scope` when I try to use this lib

**Comment by Pillar1989** [comment]
I hope you can clearly describe this problem so that we can better help you.

**Comment by A3yuu** [comment]
me too at
I2Cdev.cpp:282:54:, I2Cdev.cpp:430:62:
on M5 Atom Lite
https://github.com/jrowberg/i2cdevlib/pull/330

**Comment by KAMRANRASOOL777** [comment]
I2Cdev library provided here is outdated and will not work for non-avr architectures for arduino (e.g. ESP32). 
Update the I2Cdev.h and I2Cdev.cpp to latest. It will work. [Here](https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/I2Cdev)  is the link.
